# Generated by Django 3.0.7 on 2020-07-22 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'book')},
        ),
    ]
