# Generated by Django 3.0.7 on 2020-07-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0005_book_added_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='accomplish_nums',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
