# Generated by Django 3.0.7 on 2020-08-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0007_auto_20200728_1454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
