# Generated by Django 3.0.7 on 2020-06-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.CharField(max_length=40, verbose_name='birth_date'),
        ),
    ]
