# Generated by Django 3.0.7 on 2020-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0004_book_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_times',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
