# Generated by Django 3.0.7 on 2020-08-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0008_auto_20200803_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField()),
                ('book_id', models.CharField(max_length=128)),
            ],
            options={
                'unique_together': {('user', 'book_id')},
            },
        ),
    ]
